services:
  redis:
    container_name: redis_server
    image: redis:7.4.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: [CMD, redis-cli, -a, ping]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
    driver: local
