defaults:
  - _self_
  - /streaming: kafka

name: smartsocket_connection
provider:
  name: smartsocket
  correlation_id: smart0000_
  subscription_mode: snap_quote
  debug: false
  ping_interval: 25
  ping_message: ping
streaming: ${kafka}
symbols: null # List of stock symbols
num_connections: 3
exchange_type: NSE
current_connection_number: 0
use_thread: true
num_tokens_per_instance: 1000

################################ NOTE ################################
# If you specify the stock_symbols, then the data will be streamed only for those symbols.
# Do not enter the futures and options symbols here as it is not supported. If you do not
# specify the stock_symbols, then the data will be streamed for all the symbols that are
# available in the NSE exchange.
