defaults:
  - _self_
  - /streaming: kafka

name: uplinksocket_connection
provider:
  guid: uplink0001
  subscription_mode: ltpc # ltpc, option_greeks, full
  debug: false
  ping_interval: 25
  ping_message: ping
streaming: ${kafka}
symbols: null # List of stock symbols
num_connections: 1
exchange_type: BSE
num_tokens_per_instance: 5000
current_connection_number: 0
use_thread: true
